package com.kozvits.kislogtd.presentation.theme

import androidx.compose.ui.graphics.Color

// Material You seed color - emerald green
val Seed = Color(0xFF0D7C5C)

// Light theme
val LightPrimary = Color(0xFF0D7C5C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB0F0D7)
val LightOnPrimaryContainer = Color(0xFF002117)
val LightSecondary = Color(0xFF4B6358)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE9DA)
val LightOnSecondaryContainer = Color(0xFF082016)
val LightTertiary = Color(0xFF3D6473)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC1E8FA)
val LightOnTertiaryContainer = Color(0xFF001F29)
val LightBackground = Color(0xFFFBFDF8)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFFBFDF8)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDBE5DD)
val LightOnSurfaceVariant = Color(0xFF404943)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark theme
val DarkPrimary = Color(0xFF7DDABF)
val DarkOnPrimary = Color(0xFF00382A)
val DarkPrimaryContainer = Color(0xFF005142)
val DarkOnPrimaryContainer = Color(0xFFB0F0D7)
val DarkSecondary = Color(0xFFB3CCBE)
val DarkOnSecondary = Color(0xFF1E352A)
val DarkSecondaryContainer = Color(0xFF344B40)
val DarkOnSecondaryContainer = Color(0xFFCEE9DA)
val DarkTertiary = Color(0xFFA5CDDE)
val DarkOnTertiary = Color(0xFF073543)
val DarkTertiaryContainer = Color(0xFF234C5B)
val DarkOnTertiaryContainer = Color(0xFFC1E8FA)
val DarkBackground = Color(0xFF191C1A)
val DarkOnBackground = Color(0xFFE1E3DE)
val DarkSurface = Color(0xFF191C1A)
val DarkOnSurface = Color(0xFFE1E3DE)
val DarkSurfaceVariant = Color(0xFF404943)
val DarkOnSurfaceVariant = Color(0xFFBFC9C1)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// Category colors
val CategoryInbox = Color(0xFFE74C3C)
val CategoryDay = Color(0xFF2ECC71)
val CategoryLater = Color(0xFFF39C12)
val CategoryControl = Color(0xFF3498DB)
val CategoryMaybe = Color(0xFF9B59B6)
val CategoryProject = Color(0xFF1ABC9C)
val CategoryStem = Color(0xFF95A5A6)
val CategoryUrgent = Color(0xFFE74C3C)
